services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: smartglass-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smartglass-network

  # pgAdmin (PostgreSQL 관리 툴, 선택사항)
  pgadmin:
    image: dpage/pgadmin4
    container_name: smartglass-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smartglass.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - smartglass-network


volumes:
  postgres_data:

networks:
  smartglass-network:
    driver: bridge
